name: Obsessively Geek
favicon: null
layout_spectrum: 0.3597656439524144
typography_spectrum: 0.528846908826381
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.06814759713597596
  lightness: 0.8134124448988587
  saturation: 0.6255938650574535
  rhythmicContrast: 0.42819121363572776
purpose: []
