name: Obsessively Geek
favicon: null
layout_spectrum: 0.3597656439524144
typography_spectrum: 0.60267
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#560000'
    - '#ffffff'
    - '#bb9898'
    - '#7d3b3b'
    - '#ddcccc'
  brandStrength: 0.125
  lightness: 0.8134124448988587
  saturation: 0.6255938650574535
  rhythmicContrast: 0.42819121363572776
purpose: []
